### ISSUE TITLE
Integration with different cars

### ISSUE THREAD

**Issue by malys** [tzebrowski/ObdGraphs#26]
Hi, i'm trying to find  an easy and beautiful solution to read OBD2 data from myMG4.

ElectricSidecar community has integrated this car and provides many descriptor for EV cars.
In my case, is there an easy way to convert this descriptor https://github.com/ElectricSidecar/MG-MG4/blob/main/signalsets/v3/default.json to something compatible with your app.

For you, it could be interesting to integrate this import  and therefore to be compatible with many ev cars see https://github.com/orgs/ElectricSidecar/repositories?type=all

**Comment by tzebrowski** [comment]
Hi, sound's like a good idea, however (I might be wrong, Impression based on the first look) the stuff here (https://github.com/orgs/ElectricSidecar/repositories?type=all) is under Creative Commons License (copy left) which is not compatible with Apache License v2 which I am using...

**Comment by tzebrowski** [comment]
Creating external file most probably trigger the license as well, since the original one is the source..

**Comment by tzebrowski** [comment]
> i don't think so because information comes from reverse engineering.
License is on the file and distributions.
a user could use his own local file without impacting software licensing. is it possible to use a local descriptor and load it?

Apologize, however I am not convinced to this explanation. If you provide me different source of data with proper license (not gpl* based), then we can discuss about integration.
